# Generated by Django 5.2 on 2026-05-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50)),
                ('fecha_emision', models.DateField()),
                ('nif_emisor', models.CharField(max_length=50)),
                ('nombre_emisor', models.CharField(max_length=200)),
                ('base_imponible', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('documento_origen', models.FileField(upload_to='facturas/')),
            ],
        ),
    ]
