# Generated by Django 5.2 on 2026-05-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriagasto',
            options={'verbose_name': 'Categoría de gasto', 'verbose_name_plural': 'Categorías de gasto'},
        ),
        migrations.AlterModelOptions(
            name='factura',
            options={'ordering': ['-fecha_emision'], 'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.AlterModelOptions(
            name='lineafactura',
            options={'verbose_name': 'Línea de factura', 'verbose_name_plural': 'Líneas de factura'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AddConstraint(
            model_name='factura',
            constraint=models.UniqueConstraint(fields=('numero_factura', 'proveedor'), name='factura_unica_por_proveedor'),
        ),
    ]
