# Generated by Django 5.2 on 2026-06-01 10:06

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_alter_categoriagasto_options_alter_factura_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FragmentoNormativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fuente', models.CharField(max_length=200)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
            ],
            options={
                'verbose_name': 'Fragmento de normativa',
                'verbose_name_plural': 'Fragmentos de normativa',
            },
        ),
    ]
