# Generated by Django 5.2 on 2026-06-01 10:42

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0003_fragmentonormativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragmentonormativa',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1024),
        ),
    ]
