# Generated by Django 5.2 on 2026-06-01 10:48

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0004_alter_fragmentonormativa_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragmentonormativa',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=2048),
        ),
    ]
