# Generated by Django 5.2 on 2026-06-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0006_factura_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='error_extraccion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='factura',
            name='extraccion_fallida',
            field=models.BooleanField(default=False),
        ),
    ]
