# Generated by Django 5.2 on 2026-06-05 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0007_factura_error_extraccion_factura_extraccion_fallida'),
    ]

    operations = [
        migrations.CreateModel(
            name='SugerenciaCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_sugerencia', models.TextField()),
                ('modelo_ia_usado', models.CharField(max_length=200)),
                ('aceptada', models.BooleanField(null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturas.factura')),
            ],
            options={
                'verbose_name': 'Sugerencia de categoría',
                'verbose_name_plural': 'Sugerencias de categoría',
            },
        ),
    ]
