# Generated by Django 5.2 on 2026-05-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('identificador_fiscal', models.CharField(blank=True, default='', max_length=20)),
                ('email_contacto', models.EmailField(blank=True, default='', max_length=254)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('pais', models.CharField(default='ES', max_length=2)),
                ('moneda', models.CharField(default='EUR', max_length=3)),
                ('zona_horaria', models.CharField(default='Europe/Madrid', max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
