# Generated by Django 6.0.5 on 2026-05-19 10:45

from django.db import migrations, models

#? Se ha creado con el comando, pero no entiendo para que sirve
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_instancia', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
