# Generated by Django 5.2 on 2026-05-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='email_contacto',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='moneda',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='zona_horaria',
        ),
        migrations.AddField(
            model_name='negocio',
            name='email_contacto',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='negocio',
            name='moneda',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='negocio',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='negocio',
            name='zona_horaria',
            field=models.CharField(default='Europe/Madrid', max_length=50),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='identificador_fiscal',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
