# Generated by Django 5.2 on 2026-06-01 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_remove_perfil_creado_en_remove_perfil_email_contacto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='negocio',
            options={'verbose_name': 'Negocio', 'verbose_name_plural': 'Negocios'},
        ),
    ]
