# Generated by Django 5.2 on 2026-05-26 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('prioridad', models.PositiveSmallIntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')], default=2)),
                ('politica_reprog', models.CharField(choices=[('flexible', 'Flexible'), ('rigida', 'Rígida'), ('cancelar', 'Cancelar si no hay hueco')], default='flexible', max_length=20)),
                ('plantilla_notas', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('anotaciones', models.TextField(blank=True, default='')),
                ('prioridad', models.PositiveSmallIntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')], default=2)),
                ('repetir', models.CharField(choices=[('nunca', 'Nunca'), ('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('anual', 'Anual')], default='nunca', max_length=10)),
                ('ubicacion', models.CharField(blank=True, default='', max_length=255)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='calendario.categoria')),
            ],
            options={
                'ordering': ['inicio'],
            },
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aviso', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('notificacion', 'Notificación'), ('correo', 'Correo electrónico')], default='notificacion', max_length=15)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorio', to='calendario.cita')),
            ],
        ),
    ]
