# Generated by Django 5.2 on 2026-05-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cita',
            name='inicio',
            field=models.DateField(),
        ),
    ]
