# Generated by Django 5.2 on 2026-06-01 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0002_cita_hora_fin_cita_hora_inicio_alter_cita_fin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'categorías'},
        ),
    ]
